### ISSUE TITLE
uninitialized constant CarrierWave::Mount::Mounter

### ISSUE THREAD

**Issue by jaswinder97** [dalpo/carrierwave_globalize#1]
The following method has an issue:

 def _translations_mounter(column)
      @_translations_mounter ||= {}
      (@_translations_mounter[Globalize.locale.to_sym] ||= {})[column] ||= \
        ::CarrierWave::Mount::Mounter.new(self, column)
    end

We need to change **Carrierwave::Mount::Mounter** to **Carrierwave::Mounter**
Reference for solution: https://github.com/neo4jrb/carrierwave-neo4j/pull/11

**Comment by dalpo** [comment]
Thanks a lot @jaswinder97!
I released a new version https://rubygems.org/gems/carrierwave_globalize/versions/0.2.0.

Let me know if you will find any kind of problem :wink:
